### PR TITLE
Away timer - Automatically add time away less than 20 minutes

### PR DESCRIPTION
**Pull request by jumpkick**
This past week in testing, I've logged very little time through the extension because I've been switching between email, look at logs in terminal and running things in Eclipse.    All of those tasks are related to the working issue and I usually jump in to VS Code again within a few minutes, since VS code isn't active, the time is "lost".

This prototype sets up a countdown timeout of 20 minutes, if I return within that timeout the inactive time is added to the working time and the clock resumes.

If I don't return to VSCode within 20 minutes, than that interruption time is not logged against the task.  The timeout could be shorter by default (like 5 minutes) or not enabled at all.

Please feel free to use/not use the code... It was just something I hacked up quickly, so it's not very elegant. 😄

### CODE REVIEW

**Comment by gioboa** [comment]
Hi, can you commit in the pull request all the files? This type of approach can be better for have precise time activity.

**Comment by jumpkick** [comment]
@gioboa the only file that changed is out/src/shared/status-bar.js, there's no other files.   Not sure if that's what you mean.

**Comment by gioboa** [comment]
The source code is in src folder and in the out folder there are compiled files. if you want you can modify the src file and I merge the pull request or I take your code and I do the implementation.

**Comment by jumpkick** [comment]
Oh I got you.... Sorry about that I was hacking the loaded plugin...  I'll
see if I can fix it.

**Comment by gioboa** [comment]
Hi, what about this pull request? I can implement for you the feature if you want... I plan it in the next milestone.

**Comment by jumpkick** [comment]
Sorry really busy at work and home, might be able to do some work on it on
Thursday.

**Comment by gioboa** [comment]
Don't worry, it was only to understand if I need to schedule also this task. 😄

**Comment by jumpkick** [comment]
Not sure how to replace the pull request, so will just close this and open a new pull request

**Pull request closed without merging**
