### PR TITLE
Refactoring/configuration service updates

### PR DESCRIPTION
**Pull request by knicefire**
Small code improvements related to Configuration Service.

- Better credentials management. Removed copy-paste splitting string logic
- BASE_URL trailing slash is now handled on `set`
- Enabled native VS Code configuration feature.
  *  Variable type detection based on package.json 
  * Default values based on package.json

Further points to improvement regarding the configuration service.
- Use native [dotted](https://code.visualstudio.com/api/references/vscode-api#workspace.getConfiguration) variable key splitting 
This opens a tons of capabilities like scoped configuration which can be passed along to other objects
- Consider removing the need for globalState access, as well as setting target to global [here](https://github.com/gioboa/jira-plugin/blob/develop/src/services/configuration.service.ts#L50)
All projects are folder based or workspace based so let's be able to set different configuration for each, and this still doesn't prevent user to set global configuration
- Detect scenario when the code is ran under the test, to prevent messing up with "production" settings

### CODE REVIEW

**Comment by gioboa** [comment]
Great 👍Thanks.
How we can trace the points to improvement?

**Comment by knicefire** [comment]
I don't know exactly what you mean? 
Those are subjective I guess, but I believe they "improve" the code from the development and further support perspective. 

Having a code that is clean, and that can be easy to understand means that more developers would be willing to get involve and add more features that they need rather than "complaining" about missing some functionality.. I guess :)

**Comment by knicefire** [comment]
Ouh.. did you mean that it'd be nice to create tickets for those points that I mentioned?

**Comment by gioboa** [comment]
Yes, this can be really nice and helpful. :+1:

**Pull request merged**
