### PR TITLE
Current Sprint functionality and work state separator

### PR DESCRIPTION
**Pull request by tiago-pullup**
For agile development, current sprint and status separation are extremely necessary functionalities

### CODE REVIEW

**Comment by gioboa** [comment]
@tiago-pullup 
Really thanks for your PR. :+1: 
Soon I will check your commits.

**Comment by tiago-pullup** [comment]
I will search a little more about jql for that.

About other point I will change here and send again.

**Comment by tiago-pullup** [comment]
It's done, all changes made

**Comment by gioboa** [comment]
@tiago-pullup next week I test and publish the new release with your feature 👍

**Comment by gioboa** [comment]
@tiago-pullup [here](https://github.com/gioboa/jira-plugin/releases/tag/0.9.0) the new release.
I made some changes, but your work was really appreciated.
Thanks. 👍

**Comment by tiago-pullup** [comment]
Thank you very much, I will make further contributions as soon as possible.

**Pull request merged**
