### PR TITLE
Away timer

### PR DESCRIPTION
**Pull request by jumpkick**
Here's it patched as typescript...  I'm not sure how to test it in VSCode yet, but I thought I'd throw it over for you to look at...  I'll try to spend some time to figure out how to test it tomorrow.

### CODE REVIEW

**Comment by gioboa** [comment]
Hi. :smile:
To test your code:
1. open your project folder in VS Code (first instance)
1. run `npm install`
1. pess F5 in VS Code (start debug command)
1. another VS Code appear with your plugin (second instance)
1. now you can test

If you add some breakpoint in the first instance you can debug the second.

So far so good. :smile:

**Comment by jumpkick** [comment]
Hmm... I tried your steps (thanks btw) and it seems the debug instance always stays active for me.  At first I thought maybe the old extension install was interfering, so I closed all the VSCode instances and deleted *jira* from my .vscode/extensions folder.   Re-run, still stays active... maybe because of the debugger?   Or maybe I've introduced a bug?

**Comment by gioboa** [comment]
When you launch the debug the second instance start, from that you can try your code. If the second instance remain open it's the correct behaviour. Maybe I don't understand which is the issue... :confused:

**Comment by jumpkick** [comment]
Oh, when I first did the patch there was only on 
`(vscode.window.state.focused) `
on Line 76 of src/shared/status-bar.ts

I just noticed my patch overwrote this :( 
`vscode.window.state.focused || getConfigurationByKey(CONFIG.TRACKING_TIME_MODE) === TRACKING_TIME_MODE.ALWAYS`

My patch was to only add back the away time if the user comes back in less than X minutes, seems maybe Tracking_time_mode.always will track always even if user doesn't come back -- so overnight even?

**Comment by gioboa** [comment]
Yes, I add a plugin setting for decide the time tracking mode. If the mode is "always" and the user forget VS Code open, the plugin continue to track the time. Here the [commit](https://github.com/gioboa/jira-plugin/commit/aca8c38b1a5b2dd32170cda6f9e46b5845aa7d4d)

**Comment by jumpkick** [comment]
Think I found my problem...
need to move `this.workingIssueItem.text = this.workingIssueItemText(state.workingIssue);` to just before the timer ends, so it is called during idle periods too. :smile:

**Comment by gioboa** [comment]
I think you've done a great job. :satisfied: Really thanks for had improve the plugin. :smile:

**Comment by gioboa** [comment]
I've done a little fix in the working issue text.
For me is much cleaner.
What do you think about it?

screen shot 2018-07-31 at 11 49 17

**Comment by jumpkick** [comment]
Looks good :)

**Pull request merged**
